sed -i "s|VITE_FIREBASE_API_KEY_PLACEHOLDER|$VITE_FIREBASE_API_KEY|g" index.html
sed -i "s|VITE_FIREBASE_AUTH_DOMAIN_PLACEHOLDER|$VITE_FIREBASE_AUTH_DOMAIN|g" index.html
sed -i "s|VITE_FIREBASE_PROJECT_ID_PLACEHOLDER|$VITE_FIREBASE_PROJECT_ID|g" index.html
sed -i "s|VITE_FIREBASE_APP_ID_PLACEHOLDER|$VITE_FIREBASE_APP_ID|g" index.html
sed -i "s|VITE_FIREBASE_MESSAGING_SENDER_ID_PLACEHOLDER|$VITE_FIREBASE_MESSAGING_SENDER_ID|g" index.html
sed -i "s|VITE_GEMINI_API_KEY_PLACEHOLDER|$VITE_GEMINI_API_KEY|g" index.html

echo "Environment Variables Injected Successfully."
